import {
  alertCircleOutline,
  calendarOutline,
  checkmarkCircleOutline,
  chevronDownOutline,
  clipboardOutline,
  cloudOfflineOutline,
  ellipseOutline,
  eyeOffOutline,
  eyeOutline,
  fileTrayOutline,
  flaskOutline,
  homeOutline,
  informationCircleOutline,
  locationOutline,
  lockClosedOutline,
  logOutOutline,
  moonOutline,
  notificationsOutline,
  peopleOutline,
  personCircleOutline,
  ribbonOutline,
  refreshOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  sunnyOutline,
  timeOutline,
  trendingUpOutline,
  trophyOutline,
  warningOutline,
} from 'ionicons/icons';

/** The approved icon set. Feature code never imports ionicons directly. */
export const APP_ICONS = {
  alert: alertCircleOutline,
  calendar: calendarOutline,
  checkmark: checkmarkCircleOutline,
  chevronDown: chevronDownOutline,
  clipboard: clipboardOutline,
  dot: ellipseOutline,
  offline: cloudOfflineOutline,
  empty: fileTrayOutline,
  eye: eyeOutline,
  eyeOff: eyeOffOutline,
  flask: flaskOutline,
  home: homeOutline,
  information: informationCircleOutline,
  location: locationOutline,
  lock: lockClosedOutline,
  logOut: logOutOutline,
  moon: moonOutline,
  notifications: notificationsOutline,
  people: peopleOutline,
  person: personCircleOutline,
  refresh: refreshOutline,
  ribbon: ribbonOutline,
  settings: settingsOutline,
  shield: shieldCheckmarkOutline,
  sun: sunnyOutline,
  time: timeOutline,
  trendingUp: trendingUpOutline,
  trophy: trophyOutline,
  warning: warningOutline,
} as const;

export type AppIconName = keyof typeof APP_ICONS;

export type AppIcon = (typeof APP_ICONS)[AppIconName];
