import {
  addOutline,
  alertCircleOutline,
  arrowDownOutline,
  arrowUpOutline,
  calendarOutline,
  checkmarkCircleOutline,
  chevronDownOutline,
  clipboardOutline,
  closeOutline,
  cloudOfflineOutline,
  documentTextOutline,
  downloadOutline,
  ellipseOutline,
  eyeOffOutline,
  eyeOutline,
  fileTrayOutline,
  flaskOutline,
  globeOutline,
  homeOutline,
  informationCircleOutline,
  locationOutline,
  lockClosedOutline,
  logoFacebook,
  logoInstagram,
  logoTiktok,
  logOutOutline,
  mailOutline,
  medalOutline,
  menuOutline,
  moonOutline,
  notificationsOutline,
  peopleOutline,
  personCircleOutline,
  podiumOutline,
  ribbonOutline,
  refreshOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  stopwatchOutline,
  sunnyOutline,
  timeOutline,
  trendingUpOutline,
  trophyOutline,
  warningOutline,
} from 'ionicons/icons';

/** The approved icon set. Feature code never imports ionicons directly. */
export const APP_ICONS = {
  add: addOutline,
  alert: alertCircleOutline,
  arrowDown: arrowDownOutline,
  arrowUp: arrowUpOutline,
  calendar: calendarOutline,
  close: closeOutline,
  checkmark: checkmarkCircleOutline,
  chevronDown: chevronDownOutline,
  clipboard: clipboardOutline,
  documentText: documentTextOutline,
  dot: ellipseOutline,
  download: downloadOutline,
  offline: cloudOfflineOutline,
  empty: fileTrayOutline,
  medal: medalOutline,
  podium: podiumOutline,
  eye: eyeOutline,
  eyeOff: eyeOffOutline,
  flask: flaskOutline,
  globe: globeOutline,
  home: homeOutline,
  information: informationCircleOutline,
  location: locationOutline,
  lock: lockClosedOutline,
  logoFacebook,
  logoInstagram,
  logoTiktok,
  logOut: logOutOutline,
  mail: mailOutline,
  menu: menuOutline,
  moon: moonOutline,
  notifications: notificationsOutline,
  people: peopleOutline,
  person: personCircleOutline,
  refresh: refreshOutline,
  ribbon: ribbonOutline,
  settings: settingsOutline,
  shield: shieldCheckmarkOutline,
  statsChart: statsChartOutline,
  stopwatch: stopwatchOutline,
  sun: sunnyOutline,
  time: timeOutline,
  trendingUp: trendingUpOutline,
  trophy: trophyOutline,
  warning: warningOutline,
} as const;

export type AppIconName = keyof typeof APP_ICONS;

export type AppIcon = (typeof APP_ICONS)[AppIconName];
