/** Team and player analytics selectors. */
export const ANALYTICS_TEST_IDS = {
  analyticsPage: 'analytics-page',
  analyticsView: 'analytics-view',
  analyticsLoading: 'analytics-loading',
  analyticsError: 'analytics-error',
  analyticsOffline: 'analytics-offline',
  analyticsForbidden: 'analytics-forbidden',
  analyticsEmpty: 'analytics-empty',
  analyticsDimensionSelect: 'analytics-dimension-select',
  analyticsPeriodSelect: 'analytics-period-select',
  analyticsSeriesChart: 'analytics-series-chart',
  analyticsSeriesSummary: 'analytics-series-summary',
  analyticsGapNotice: 'analytics-gap-notice',
  analyticsDirectionLegend: 'analytics-direction-legend',
  analyticsCohortPanel: 'analytics-cohort-panel',
  analyticsCohortPeriodSelect: 'analytics-cohort-period-select',
  analyticsCohortTiles: 'analytics-cohort-tiles',
  analyticsCohortSuppressed: 'analytics-cohort-suppressed',
  analyticsFreshnessCard: 'analytics-freshness-card',
  analyticsStaleBadge: 'analytics-stale-badge',
  analyticsRebuildOpen: 'analytics-rebuild-open',
  analyticsRebuildDialog: 'analytics-rebuild-dialog',
  analyticsRebuildConfirm: 'analytics-rebuild-confirm',
  analyticsRebuildCancel: 'analytics-rebuild-cancel',
  analyticsRebuildReport: 'analytics-rebuild-report',
  analyticsPlayerSelect: 'analytics-player-select',

  playerAnalyticsPage: 'player-analytics-page',
  playerAnalyticsView: 'player-analytics-view',
  playerAnalyticsLoading: 'player-analytics-loading',
  playerAnalyticsError: 'player-analytics-error',
  playerAnalyticsOffline: 'player-analytics-offline',
  playerAnalyticsForbidden: 'player-analytics-forbidden',
  playerAnalyticsEmpty: 'player-analytics-empty',
  playerAnalyticsIdentity: 'player-analytics-identity',
  playerAnalyticsBack: 'player-analytics-back',
  memberProfileAnalyticsLink: 'member-profile-analytics-link',
} as const;
