/**
 * Canonical route table. Modules expose typed builders in their
 * routes/*.paths.ts files derived from these values; raw route strings are
 * forbidden everywhere else (ESLint: architecture/no-inline-routes).
 */
export const APP_PATHS = {
  root: '/',
  welcome: '/welcome',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  acceptInvitation: '/accept-invitation',
  sessions: '/sessions',
  home: '/home',
  practices: '/practices',
  practiceSession: '/practices/:sessionId',
  attendance: '/practices/:sessionId/attendance',
  admin: '/admin',
  members: '/members',
  memberProfile: '/members/:membershipId',
  assessments: '/assessments',
  assessmentEntry: '/assessments/:assessmentId',
  performance: '/performance',
  training: '/training',
  trainingSubmission: '/training/:submissionId',
  trainingReview: '/training-review',
  leaderboard: '/leaderboard',
  points: '/points',
  competitions: '/competitions',
  competitionDetail: '/competitions/:competitionId',
  squads: '/squads',
  squadDetail: '/squads/:squadId',
  rosters: '/rosters',
  rosterDetail: '/rosters/:rosterId',
  tryoutRegistration: '/tryout-registration',
  tryouts: '/tryouts',
  tryoutDetail: '/tryouts/:tryoutId',
  matches: '/matches',
  matchScoreboard: '/matches/:matchId',
  matchStatistics: '/matches/:matchId/statistics',
  notifications: '/notifications',
  notificationPreferences: '/notifications/preferences',
  notificationLink: '/notifications/open/:notificationId',
  adminSettings: '/admin/settings',
  adminRoles: '/admin/roles',
  adminRules: '/admin/rules',
  adminOperations: '/admin/operations',
  adminTeams: '/admin/teams',
  adminSeasons: '/admin/seasons',
  adminPermissions: '/admin/permissions',
  settings: '/settings',
  workbench: '/workbench',
} as const;

export type AppPath = (typeof APP_PATHS)[keyof typeof APP_PATHS];
