/**
 * Assessments and performance (measurements, feedback, development goals)
 * test ids. Split out of the aggregate catalog so TEST_IDS stays within its
 * size budget.
 */
export const ASSESSMENTS_TEST_IDS = {
  assessmentsPage: 'assessments-page',
  assessmentsView: 'assessments-view',
  assessmentsLoading: 'assessments-loading',
  assessmentsError: 'assessments-error',
  assessmentsOffline: 'assessments-offline',
  assessmentsEmpty: 'assessments-empty',
  assessmentsForbidden: 'assessments-forbidden',
  assessmentsPeriodFilter: 'assessments-period-filter',
  assessmentsStatusFilter: 'assessments-status-filter',
  assessmentsList: 'assessments-list',
  assessmentSummaryCard: 'assessment-summary-card',
  assessmentStatusChip: 'assessment-status-chip',
  assessmentEntryPage: 'assessment-entry-page',
  assessmentEntryView: 'assessment-entry-view',
  assessmentEntryLoading: 'assessment-entry-loading',
  assessmentEntryError: 'assessment-entry-error',
  assessmentEntryForbidden: 'assessment-entry-forbidden',
  assessmentEntryBack: 'assessment-entry-back',
  assessmentMetricGrid: 'assessment-metric-grid',
  assessmentMetricField: 'assessment-metric-field',
  assessmentMetricScore: 'assessment-metric-score',
  assessmentMetricNumber: 'assessment-metric-number',
  assessmentMetricText: 'assessment-metric-text',
  assessmentMetricNote: 'assessment-metric-note',
  assessmentMetricNotEvaluated: 'assessment-metric-not-evaluated',
  assessmentMetricValueReadout: 'assessment-metric-value-readout',
  assessmentCompleteness: 'assessment-completeness',
  assessmentWorkflowBar: 'assessment-workflow-bar',
  assessmentSaveDraft: 'assessment-save-draft',
  assessmentSubmit: 'assessment-submit',
  assessmentStartReview: 'assessment-start-review',
  assessmentApprove: 'assessment-approve',
  assessmentReject: 'assessment-reject',
  assessmentPublish: 'assessment-publish',
  assessmentRevisionList: 'assessment-revision-list',
  assessmentSummaryNote: 'assessment-summary-note',
  performancePage: 'performance-page',
  performanceView: 'performance-view',
  performanceLoading: 'performance-loading',
  performanceError: 'performance-error',
  performanceOffline: 'performance-offline',
  performanceEmpty: 'performance-empty',
  performanceForbidden: 'performance-forbidden',
  performanceTrendChart: 'performance-trend-chart',
  performanceRadarChart: 'performance-radar-chart',
  performanceMetricSelect: 'performance-metric-select',
  chartDataTable: 'chart-data-table',
  chartDataToggle: 'chart-data-toggle',
  coachFeedbackPanel: 'coach-feedback-panel',
  coachFeedbackCard: 'coach-feedback-card',
  coachFeedbackAcknowledge: 'coach-feedback-acknowledge',
  coachFeedbackClarify: 'coach-feedback-clarify',
  developmentGoalsPanel: 'development-goals-panel',
  developmentGoalCard: 'development-goal-card',
  developmentGoalProgress: 'development-goal-progress',
  developmentGoalAction: 'development-goal-action',
  developmentGoalTransition: 'development-goal-transition',
} as const;
