/**
 * Competition, squad, eligibility, and roster test ids (prompt 810). Split out
 * of the aggregate catalog so TEST_IDS stays within its size budget; raw test
 * ids remain forbidden everywhere else (ESLint: architecture/no-inline-test-ids).
 */
export const COMPETITIONS_TEST_IDS = {
  competitionsPage: 'competitions-page',
  competitionsView: 'competitions-view',
  competitionsLoading: 'competitions-loading',
  competitionsError: 'competitions-error',
  competitionsOffline: 'competitions-offline',
  competitionsForbidden: 'competitions-forbidden',
  competitionsEmpty: 'competitions-empty',
  competitionsStatusFilter: 'competitions-status-filter',
  competitionsTypeFilter: 'competitions-type-filter',
  competitionsList: 'competitions-list',
  competitionCard: 'competition-card',
  competitionOpen: 'competition-open',
  competitionDetailPage: 'competition-detail-page',
  competitionDetailView: 'competition-detail-view',
  competitionSummary: 'competition-summary',
  competitionStages: 'competition-stages',
  competitionStage: 'competition-stage',
  competitionRound: 'competition-round',
  competitionFixtures: 'competition-fixtures',
  competitionFixture: 'competition-fixture',
  competitionOpponents: 'competition-opponents',
  competitionOpponent: 'competition-opponent',
  competitionBack: 'competition-back',
  squadsPage: 'squads-page',
  squadsView: 'squads-view',
  squadsStatusFilter: 'squads-status-filter',
  squadsList: 'squads-list',
  squadCard: 'squad-card',
  squadOpen: 'squad-open',
  squadDetailPage: 'squad-detail-page',
  squadDetailView: 'squad-detail-view',
  squadHeader: 'squad-header',
  squadRatio: 'squad-ratio',
  squadTransition: 'squad-transition',
  squadEligibilityPanel: 'squad-eligibility-panel',
  squadEligibilityRow: 'squad-eligibility-row',
  squadEligibilitySignal: 'squad-eligibility-signal',
  squadEligibilityAdvisory: 'squad-eligibility-advisory',
  squadSelectAction: 'squad-select-action',
  squadRemoveAction: 'squad-remove-action',
  squadOverridePanel: 'squad-override-panel',
  squadOverrideReason: 'squad-override-reason',
  squadOverrideConfirm: 'squad-override-confirm',
  squadOverrideCancel: 'squad-override-cancel',
  squadAvailabilityPanel: 'squad-availability-panel',
  squadAvailabilitySelect: 'squad-availability-select',
  squadAvailabilityReason: 'squad-availability-reason',
  squadAvailabilitySubmit: 'squad-availability-submit',
  squadAvailabilityRow: 'squad-availability-row',
  squadRosterPanel: 'squad-roster-panel',
  squadRosterRow: 'squad-roster-row',
  squadRosterPendingNotice: 'squad-roster-pending-notice',
  rostersPage: 'rosters-page',
  rostersView: 'rosters-view',
  rostersKindFilter: 'rosters-kind-filter',
  rostersList: 'rosters-list',
  rosterCard: 'roster-card',
  rosterOpen: 'roster-open',
  rosterDetailPage: 'roster-detail-page',
  rosterDetailView: 'roster-detail-view',
  rosterHeader: 'roster-header',
  rosterAction: 'roster-action',
  rosterValidationPanel: 'roster-validation-panel',
  rosterViolation: 'roster-violation',
  rosterEntriesPanel: 'roster-entries-panel',
  rosterEntryRow: 'roster-entry-row',
  rosterEntryRemove: 'roster-entry-remove',
  rosterHistoryPanel: 'roster-history-panel',
  rosterHistoryRow: 'roster-history-row',
} as const;
