/**
 * Public landing page (`/`) test ids. Split out of the aggregate catalog so
 * TEST_IDS stays within its size budget.
 */
export const LANDING_TEST_IDS = {
  landingPage: 'landing-page',
  landingHero: 'landing-hero',
  landingHeroPrimaryCta: 'landing-hero-primary-cta',
  landingHeroSecondaryCta: 'landing-hero-secondary-cta',
  landingExplainer: 'landing-explainer',
  landingAboutPreview: 'landing-about-preview',
  landingAboutPreviewCta: 'landing-about-preview-cta',
  landingStaff: 'landing-staff',
  landingStaffCard: 'landing-staff-card',
  landingStaffLoading: 'landing-staff-loading',
  landingStaffError: 'landing-staff-error',
  landingStaffOffline: 'landing-staff-offline',
  landingStaffForbidden: 'landing-staff-forbidden',
  landingStaffEmpty: 'landing-staff-empty',
  landingPlayers: 'landing-players',
  landingPlayersLoading: 'landing-players-loading',
  landingPlayersError: 'landing-players-error',
  landingPlayersOffline: 'landing-players-offline',
  landingPlayersForbidden: 'landing-players-forbidden',
  landingPlayersEmpty: 'landing-players-empty',
  landingCompetitions: 'landing-competitions',
  landingCompetitionCard: 'landing-competition-card',
  landingCompetitionsLoading: 'landing-competitions-loading',
  landingCompetitionsError: 'landing-competitions-error',
  landingCompetitionsOffline: 'landing-competitions-offline',
  landingCompetitionsForbidden: 'landing-competitions-forbidden',
  landingCompetitionsEmpty: 'landing-competitions-empty',
  landingMatches: 'landing-matches',
  landingMatchesLoading: 'landing-matches-loading',
  landingMatchesError: 'landing-matches-error',
  landingMatchesOffline: 'landing-matches-offline',
  landingMatchesForbidden: 'landing-matches-forbidden',
  landingMatchesEmpty: 'landing-matches-empty',
  landingLeaderboard: 'landing-leaderboard',
  landingLeaderboardLoading: 'landing-leaderboard-loading',
  landingLeaderboardError: 'landing-leaderboard-error',
  landingLeaderboardOffline: 'landing-leaderboard-offline',
  landingLeaderboardForbidden: 'landing-leaderboard-forbidden',
  landingLeaderboardEmpty: 'landing-leaderboard-empty',
  landingNews: 'landing-news',
  landingNewsLoading: 'landing-news-loading',
  landingNewsError: 'landing-news-error',
  landingNewsOffline: 'landing-news-offline',
  landingNewsForbidden: 'landing-news-forbidden',
  landingNewsEmpty: 'landing-news-empty',
  landingSpiritValues: 'landing-spirit-values',
  landingLocation: 'landing-location',
  landingLocationCta: 'landing-location-cta',
  landingGallery: 'landing-gallery',
  landingGalleryTile: 'landing-gallery-tile',
  landingAchievements: 'landing-achievements',
  landingSocial: 'landing-social',
  landingSocialLink: 'landing-social-link',
  landingFinalCta: 'landing-final-cta',
  landingFinalCtaPrimary: 'landing-final-cta-primary',
  landingFinalCtaSecondary: 'landing-final-cta-secondary',
  spiritValuesGrid: 'spirit-values-grid',
  spiritValueCard: 'spirit-value-card',
} as const;
