/**
 * Live scoreboard, offline scorekeeper, and match statistics test ids
 * (prompts 811 and 812). Split out of the aggregate catalog so TEST_IDS stays
 * within its size budget; raw test ids remain forbidden everywhere else
 * (ESLint: architecture/no-inline-test-ids).
 */
export const MATCHES_TEST_IDS = {
  matchesPage: 'matches-page',
  matchesView: 'matches-view',
  matchesLoading: 'matches-loading',
  matchesError: 'matches-error',
  matchesOffline: 'matches-offline',
  matchesForbidden: 'matches-forbidden',
  matchesEmpty: 'matches-empty',
  matchesStatusFilter: 'matches-status-filter',
  matchesList: 'matches-list',
  matchCard: 'match-card',
  matchOpenScoreboard: 'match-open-scoreboard',
  matchOpenStatistics: 'match-open-statistics',

  scoreboardPage: 'scoreboard-page',
  scoreboardView: 'scoreboard-view',
  scoreboardLoading: 'scoreboard-loading',
  scoreboardError: 'scoreboard-error',
  scoreboardOffline: 'scoreboard-offline',
  scoreboardForbidden: 'scoreboard-forbidden',
  scoreboardEmpty: 'scoreboard-empty',
  scoreboardBack: 'scoreboard-back',
  scoreboardScore: 'scoreboard-score',
  scoreboardOurScore: 'scoreboard-our-score',
  scoreboardTheirScore: 'scoreboard-their-score',
  scoreboardStatus: 'scoreboard-status',
  scoreboardLive: 'scoreboard-live',
  scoreboardRules: 'scoreboard-rules',
  scoreboardScoring: 'scoreboard-scoring',
  scoreboardPointUs: 'scoreboard-point-us',
  scoreboardPointThem: 'scoreboard-point-them',
  scoreboardScorerSelect: 'scoreboard-scorer-select',
  scoreboardAssistSelect: 'scoreboard-assist-select',
  scoreboardTimeouts: 'scoreboard-timeouts',
  scoreboardTimeoutUs: 'scoreboard-timeout-us',
  scoreboardTimeoutThem: 'scoreboard-timeout-them',
  scoreboardState: 'scoreboard-state',
  scoreboardTransition: 'scoreboard-transition',
  scoreboardTimeline: 'scoreboard-timeline',
  scoreboardTimelineRow: 'scoreboard-timeline-row',
  scoreboardUndo: 'scoreboard-undo',
  scoreboardUndoReason: 'scoreboard-undo-reason',
  scoreboardUndoConfirm: 'scoreboard-undo-confirm',
  scoreboardFinalize: 'scoreboard-finalize',
  scoreboardFinalizeAction: 'scoreboard-finalize-action',
  scoreboardFinalizeBlocked: 'scoreboard-finalize-blocked',

  scorekeeperQueue: 'scorekeeper-queue',
  scorekeeperQueueBadge: 'scorekeeper-queue-badge',
  scorekeeperQueueRow: 'scorekeeper-queue-row',
  scorekeeperQueueRetry: 'scorekeeper-queue-retry',
  scorekeeperQueueLimit: 'scorekeeper-queue-limit',
  scorekeeperQueueOtherAccount: 'scorekeeper-queue-other-account',
  scorekeeperConflict: 'scorekeeper-conflict',
  scorekeeperConflictRow: 'scorekeeper-conflict-row',
  scorekeeperConflictDiscard: 'scorekeeper-conflict-discard',
  scorekeeperConflictReload: 'scorekeeper-conflict-reload',

  matchStatsPage: 'match-stats-page',
  matchStatsView: 'match-stats-view',
  matchStatsLoading: 'match-stats-loading',
  matchStatsError: 'match-stats-error',
  matchStatsOffline: 'match-stats-offline',
  matchStatsForbidden: 'match-stats-forbidden',
  matchStatsEmpty: 'match-stats-empty',
  matchStatsBack: 'match-stats-back',
  matchStatsTeam: 'match-stats-team',
  matchStatsChart: 'match-stats-chart',
  matchStatsPlayers: 'match-stats-players',
  matchStatsPlayerRow: 'match-stats-player-row',
  matchStatsPlayerOpen: 'match-stats-player-open',
  matchStatsReport: 'match-stats-report',
  matchStatsGlossary: 'match-stats-glossary',
  matchStatsDerivation: 'match-stats-derivation',
  matchStatsVideo: 'match-stats-video',
} as const;
