/**
 * Newsroom test ids (public list, article detail, permissioned editor). Split
 * out of the aggregate catalog so TEST_IDS stays within its size budget.
 */
export const NEWS_TEST_IDS = {
  newsPage: 'news-page',
  newsView: 'news-view',
  newsLoading: 'news-loading',
  newsError: 'news-error',
  newsOffline: 'news-offline',
  newsForbidden: 'news-forbidden',
  newsEmpty: 'news-empty',
  newsList: 'news-list',
  newsCard: 'news-card',
  newsCardCover: 'news-card-cover',
  newsCardFallback: 'news-card-fallback',
  newsArticlePage: 'news-article-page',
  newsArticleView: 'news-article-view',
  newsArticleLoading: 'news-article-loading',
  newsArticleError: 'news-article-error',
  newsArticleOffline: 'news-article-offline',
  newsArticleForbidden: 'news-article-forbidden',
  newsArticleEmpty: 'news-article-empty',
  newsArticleBody: 'news-article-body',
  newsArticleCover: 'news-article-cover',
  newsArticleBack: 'news-article-back',
  newsEditorPage: 'news-editor-page',
  newsEditorView: 'news-editor-view',
  newsEditorLoading: 'news-editor-loading',
  newsEditorError: 'news-editor-error',
  newsEditorOffline: 'news-editor-offline',
  newsEditorForbidden: 'news-editor-forbidden',
  newsEditorEmpty: 'news-editor-empty',
  newsEditorList: 'news-editor-list',
  newsEditorRow: 'news-editor-row',
  newsEditorRowEdit: 'news-editor-row-edit',
  newsEditorRowPublish: 'news-editor-row-publish',
  newsEditorNewDraft: 'news-editor-new-draft',
  newsEditorForm: 'news-editor-form',
  newsEditorRevisionNotice: 'news-editor-revision-notice',
  newsEditorTitleInput: 'news-editor-title-input',
  newsEditorBodyInput: 'news-editor-body-input',
  newsEditorCoverInput: 'news-editor-cover-input',
  newsEditorCompetitionInput: 'news-editor-competition-input',
  newsEditorMatchInput: 'news-editor-match-input',
  newsEditorSubmit: 'news-editor-submit',
  newsEditorCancel: 'news-editor-cancel',
} as const;
