/**
 * Notification inbox, preference, and deep-link test ids (prompt 815). Split
 * out of the aggregate catalog so TEST_IDS stays within its size budget; raw
 * test ids remain forbidden everywhere else.
 */
export const NOTIFICATIONS_TEST_IDS = {
  notificationsPage: 'notifications-page',
  notificationsView: 'notifications-view',
  notificationsLoading: 'notifications-loading',
  notificationsError: 'notifications-error',
  notificationsOffline: 'notifications-offline',
  notificationsForbidden: 'notifications-forbidden',
  notificationsEmpty: 'notifications-empty',
  notificationsStatusFilter: 'notifications-status-filter',
  notificationsCategoryFilter: 'notifications-category-filter',
  notificationsGroup: 'notifications-group',
  notificationItem: 'notification-item',
  notificationOpen: 'notification-open',
  notificationMarkRead: 'notification-mark-read',
  notificationDelivery: 'notification-delivery',
  notificationsMarkAllRead: 'notifications-mark-all-read',
  notificationsLoadMore: 'notifications-load-more',
  notificationsBoundedNotice: 'notifications-bounded-notice',
  notificationsPreferencesLink: 'notifications-preferences-link',
  notificationsDeliveryNotice: 'notifications-delivery-notice',
  notificationPrefsPage: 'notification-prefs-page',
  notificationPrefsView: 'notification-prefs-view',
  notificationPrefsLoading: 'notification-prefs-loading',
  notificationPrefsError: 'notification-prefs-error',
  notificationPrefsOffline: 'notification-prefs-offline',
  notificationPrefsForbidden: 'notification-prefs-forbidden',
  notificationPrefsEmpty: 'notification-prefs-empty',
  notificationPrefsMatrix: 'notification-prefs-matrix',
  notificationPrefsRow: 'notification-prefs-row',
  notificationPrefsToggle: 'notification-prefs-toggle',
  notificationPrefsMandatory: 'notification-prefs-mandatory',
  notificationPrefsScope: 'notification-prefs-scope',
  quietHoursPanel: 'quiet-hours-panel',
  quietHoursStart: 'quiet-hours-start',
  quietHoursEnd: 'quiet-hours-end',
  quietHoursTimezone: 'quiet-hours-timezone',
  quietHoursUrgent: 'quiet-hours-urgent',
  quietHoursSave: 'quiet-hours-save',
  notificationLinkPage: 'notification-link-page',
  notificationLinkView: 'notification-link-view',
  notificationLinkLoading: 'notification-link-loading',
  notificationLinkError: 'notification-link-error',
  notificationLinkOffline: 'notification-link-offline',
  notificationLinkForbidden: 'notification-link-forbidden',
  notificationLinkEmpty: 'notification-link-empty',
  notificationLinkBack: 'notification-link-back',
} as const;
