/** practiceRsvpDetail screen selectors. */
export const PRACTICE_RSVP_DETAIL_TEST_IDS = {
  practiceRsvpDetailPage: 'practice-rsvp-detail-page',
  practiceRsvpDetailLoading: 'practice-rsvp-detail-loading',
  practiceRsvpDetailError: 'practice-rsvp-detail-error',
  practiceRsvpDetailForbidden: 'practice-rsvp-detail-forbidden',
  practiceRsvpDetailSummary: 'practice-rsvp-detail-summary',
  practiceRsvpDetailStatusFilter: 'practice-rsvp-detail-status-filter',
  practiceRsvpDetailCount: 'practice-rsvp-detail-count',
  practiceRsvpDetailRoster: 'practice-rsvp-detail-roster',
  practiceRsvpDetailRosterRow: 'practice-rsvp-detail-roster-row',
  practiceRsvpDetailRosterEmpty: 'practice-rsvp-detail-roster-empty',
  practiceRsvpDetailOverrideAction: 'practice-rsvp-detail-override-action',
  practiceRsvpDetailHistoryAction: 'practice-rsvp-detail-history-action',
  practiceRsvpDetailLoadMore: 'practice-rsvp-detail-load-more',
  practiceRsvpDetailOverridePanel: 'practice-rsvp-detail-override-panel',
  practiceRsvpDetailOverrideStatus: 'practice-rsvp-detail-override-status',
  practiceRsvpDetailOverrideReason: 'practice-rsvp-detail-override-reason',
  practiceRsvpDetailOverrideReasonCategory: 'practice-rsvp-detail-override-reason-category',
  practiceRsvpDetailOverrideNote: 'practice-rsvp-detail-override-note',
  practiceRsvpDetailOverrideNoteVisibility: 'practice-rsvp-detail-override-note-visibility',
  practiceRsvpDetailOverrideSubmit: 'practice-rsvp-detail-override-submit',
  practiceRsvpDetailOverrideCancel: 'practice-rsvp-detail-override-cancel',
  practiceRsvpDetailHistoryPanel: 'practice-rsvp-detail-history-panel',
  practiceRsvpDetailHistoryItem: 'practice-rsvp-detail-history-item',
  practiceRsvpDetailHistoryClose: 'practice-rsvp-detail-history-close',
} as const;
