/** practiceSchedules screen selectors: the list and the create/edit screen. */
export const PRACTICE_SCHEDULES_TEST_IDS = {
  practiceSchedulesPage: 'practice-schedules-page',
  practiceSchedulesLoading: 'practice-schedules-loading',
  practiceSchedulesError: 'practice-schedules-error',
  practiceSchedulesForbidden: 'practice-schedules-forbidden',
  practiceSchedulesEmpty: 'practice-schedules-empty',
  practiceSchedulesNew: 'practice-schedules-new',
  practiceSchedulesList: 'practice-schedules-list',
  practiceScheduleRow: 'practice-schedule-row',
  practiceScheduleDetailPage: 'practice-schedule-detail-page',
  practiceScheduleDetailLoading: 'practice-schedule-detail-loading',
  practiceScheduleDetailError: 'practice-schedule-detail-error',
  practiceScheduleDetailForbidden: 'practice-schedule-detail-forbidden',
  practiceScheduleBack: 'practice-schedule-back',
  practiceScheduleStatus: 'practice-schedule-status',
  practiceScheduleForm: 'practice-schedule-form',
  practiceScheduleNameInput: 'practice-schedule-name-input',
  practiceScheduleSessionTypeInput: 'practice-schedule-session-type-input',
  practiceScheduleFrequencySelect: 'practice-schedule-frequency-select',
  practiceScheduleWeekdayToggle: 'practice-schedule-weekday-toggle',
  practiceScheduleIntervalInput: 'practice-schedule-interval-input',
  practiceScheduleStartTimeInput: 'practice-schedule-start-time-input',
  practiceScheduleDurationInput: 'practice-schedule-duration-input',
  practiceScheduleTimezoneInput: 'practice-schedule-timezone-input',
  practiceScheduleGenerationStartInput: 'practice-schedule-generation-start-input',
  practiceScheduleGenerationUntilInput: 'practice-schedule-generation-until-input',
  practiceScheduleVisibilitySelect: 'practice-schedule-visibility-select',
  practiceScheduleCapacityInput: 'practice-schedule-capacity-input',
  practiceScheduleNotesInput: 'practice-schedule-notes-input',
  practiceScheduleSave: 'practice-schedule-save',
  practiceScheduleDelete: 'practice-schedule-delete',
  practiceScheduleGenerate: 'practice-schedule-generate',
  practiceScheduleMessages: 'practice-schedule-messages',
} as const;
