/** practiceAgendaGroups screen selectors. */
export const PRACTICE_AGENDA_GROUPS_TEST_IDS = {
  practiceAgendaGroupsPage: 'practice-agenda-groups-page',
  practiceAgendaGroupsLoading: 'practice-agenda-groups-loading',
  practiceAgendaGroupsError: 'practice-agenda-groups-error',
  practiceAgendaGroupsForbidden: 'practice-agenda-groups-forbidden',
  practiceAgendaGroupsNotice: 'practice-agenda-groups-notice',
  practiceAgendaGroupsStatus: 'practice-agenda-groups-status',
  practiceAgendaGroupsPlan: 'practice-agenda-groups-plan',
  practiceAgendaGroupsPlanEmpty: 'practice-agenda-groups-plan-empty',
  practiceAgendaGroupsBlockRow: 'practice-agenda-groups-block-row',
  practiceAgendaGroupsGroups: 'practice-agenda-groups-groups',
  practiceAgendaGroupsGroupsEmpty: 'practice-agenda-groups-groups-empty',
  practiceAgendaGroupsGroupRow: 'practice-agenda-groups-group-row',
  practiceAgendaGroupsGroupSwatch: 'practice-agenda-groups-group-swatch',
  practiceAgendaGroupsGroupMembers: 'practice-agenda-groups-group-members',
  practiceAgendaGroupsMemberItem: 'practice-agenda-groups-member-item',
  practiceAgendaGroupsMemberRemove: 'practice-agenda-groups-member-remove',
  practiceAgendaGroupsGroupRemove: 'practice-agenda-groups-group-remove',
  practiceAgendaGroupsAddMemberInput: 'practice-agenda-groups-add-member-input',
  practiceAgendaGroupsAddMemberSubmit: 'practice-agenda-groups-add-member-submit',
  practiceAgendaGroupsCreateForm: 'practice-agenda-groups-create-form',
  practiceAgendaGroupsCreateName: 'practice-agenda-groups-create-name',
  practiceAgendaGroupsCreateColor: 'practice-agenda-groups-create-color',
  practiceAgendaGroupsCreateCoach: 'practice-agenda-groups-create-coach',
  practiceAgendaGroupsCreateNotes: 'practice-agenda-groups-create-notes',
  practiceAgendaGroupsCreateSubmit: 'practice-agenda-groups-create-submit',
  practiceAgendaGroupsCopyForm: 'practice-agenda-groups-copy-form',
  practiceAgendaGroupsCopySource: 'practice-agenda-groups-copy-source',
  practiceAgendaGroupsCopySubmit: 'practice-agenda-groups-copy-submit',
} as const;
