/** Reports center selectors. */
export const REPORTS_TEST_IDS = {
  reportsPage: 'reports-page',
  reportsView: 'reports-view',
  reportsLoading: 'reports-loading',
  reportsError: 'reports-error',
  reportsOffline: 'reports-offline',
  reportsForbidden: 'reports-forbidden',
  reportsEmpty: 'reports-empty',
  reportRequestPanel: 'report-request-panel',
  reportTemplateOption: 'report-template-option',
  reportFormatSelect: 'report-format-select',
  reportSeasonSelect: 'report-season-select',
  reportRequestSubmit: 'report-request-submit',
  reportRequestError: 'report-request-error',
  reportJobList: 'report-job-list',
  reportJobRow: 'report-job-row',
  reportStatusChip: 'report-status-chip',
  reportJobProgress: 'report-job-progress',
  reportJobCountdown: 'report-job-countdown',
  reportJobFailure: 'report-job-failure',
  reportDownloadButton: 'report-download-button',
  reportRetryButton: 'report-retry-button',
  reportRequestAgainButton: 'report-request-again-button',
  reportJobExpand: 'report-job-expand',
  reportJobDetail: 'report-job-detail',
  reportsRefresh: 'reports-refresh',
  reportsSlowPollNotice: 'reports-slow-poll-notice',
  reportsTemplateFilter: 'reports-template-filter',
  reportsStatusFilter: 'reports-status-filter',
  reportsPager: 'reports-pager',
  reportsPagerNext: 'reports-pager-next',
  reportsPagerPrevious: 'reports-pager-previous',
} as const;
