/**
 * Tryout registration, check-in, evaluation, decision, and conversion test ids
 * (prompt 813). Split out of the aggregate catalog so TEST_IDS stays within its
 * size budget; raw test ids remain forbidden everywhere else.
 */
export const TRYOUTS_TEST_IDS = {
  tryoutRegistrationPage: 'tryout-registration-page',
  tryoutRegistrationView: 'tryout-registration-view',
  tryoutRegistrationEvent: 'tryout-registration-event',
  tryoutRegistrationName: 'tryout-registration-name',
  tryoutRegistrationPreferred: 'tryout-registration-preferred',
  tryoutRegistrationEmail: 'tryout-registration-email',
  tryoutRegistrationPhone: 'tryout-registration-phone',
  tryoutRegistrationBirthYear: 'tryout-registration-birth-year',
  tryoutRegistrationConsent: 'tryout-registration-consent',
  tryoutRegistrationPrivacy: 'tryout-registration-privacy',
  tryoutRegistrationSubmit: 'tryout-registration-submit',
  tryoutRegistrationSuccess: 'tryout-registration-success',
  tryoutRegistrationError: 'tryout-registration-error',
  tryoutRegistrationCapacity: 'tryout-registration-capacity',
  tryoutsPage: 'tryouts-page',
  tryoutsView: 'tryouts-view',
  tryoutsLoading: 'tryouts-loading',
  tryoutsError: 'tryouts-error',
  tryoutsOffline: 'tryouts-offline',
  tryoutsForbidden: 'tryouts-forbidden',
  tryoutsEmpty: 'tryouts-empty',
  tryoutsList: 'tryouts-list',
  tryoutCard: 'tryout-card',
  tryoutOpen: 'tryout-open',
  tryoutBackendPending: 'tryout-backend-pending',
  tryoutDetailPage: 'tryout-detail-page',
  tryoutDetailView: 'tryout-detail-view',
  tryoutCapacity: 'tryout-capacity',
  tryoutStatusFilter: 'tryout-status-filter',
  tryoutCandidateList: 'tryout-candidate-list',
  tryoutCandidateRow: 'tryout-candidate-row',
  tryoutCandidateOpen: 'tryout-candidate-open',
  tryoutCheckIn: 'tryout-check-in',
  tryoutCandidatePanel: 'tryout-candidate-panel',
  tryoutContacts: 'tryout-contacts',
  tryoutContactsRestricted: 'tryout-contacts-restricted',
  tryoutReadiness: 'tryout-readiness',
  tryoutReadinessRestricted: 'tryout-readiness-restricted',
  tryoutEvaluationPanel: 'tryout-evaluation-panel',
  tryoutEvaluationScore: 'tryout-evaluation-score',
  tryoutEvaluationNote: 'tryout-evaluation-note',
  tryoutEvaluationSubmit: 'tryout-evaluation-submit',
  tryoutDecisionPanel: 'tryout-decision-panel',
  tryoutDecisionReason: 'tryout-decision-reason',
  tryoutDecisionAccept: 'tryout-decision-accept',
  tryoutDecisionWaitlist: 'tryout-decision-waitlist',
  tryoutDecisionDecline: 'tryout-decision-decline',
  tryoutConversionPanel: 'tryout-conversion-panel',
  tryoutConversionPreview: 'tryout-conversion-preview',
  tryoutConversionConfirm: 'tryout-conversion-confirm',
} as const;
