import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import { PACKAGE_OWNERSHIP } from '../../../eslint/package-ownership.config.mjs';
import { buildInventory, GOVERNANCE_VERSION } from './inventory.mjs';

export const GENERATED_HEADER =
  '<!-- GENERATED by scripts/knowledge (npm run knowledge:build); DO NOT EDIT. Canonical truth lives in rules/, skills/, agents/, context/, memory/, architecture/adrs/, docs/. -->';

function writeGenerated(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.endsWith('\n') ? content : `${content}\n`);
}

function bootstrapMarkdown() {
  return `${GENERATED_HEADER}

# AI Bootstrap

Purpose: strict Ionic React + Capacitor application (Capacitor Ranger) with Axios/NestJS API
boundaries, one-owner package facades, module-first features, generated governance context, and
mandatory quality gates.

Authority order:

1. Security/privacy policy and active ADRs (architecture/adrs/).
2. Normative rules (rules/).
3. Public contracts and schemas (docs/api/, module schemas).
4. Module guides (src/modules/*/README.md).
5. Source and tests as implementation evidence.
6. Generated \`.ai\` summaries as routing aids only.

Workflow:

1. Classify the task (see risk-lanes.md).
2. Resolve only relevant context: \`npm run knowledge:context -- --task="<exact task>"\`.
3. Read the exact implementation and its tests.
4. Plan from verified behavior.
5. Implement the smallest architecture-correct change (bottom-up).
6. Run targeted tests, then risk-appropriate gates.
7. Update canonical knowledge.
8. Rebuild \`.ai\` (\`npm run knowledge:build\`).

Never weaken authentication, package ownership, module boundaries, type safety, accessibility,
localization, native safety, tests, or rollback readiness.
`;
}

function readmeMarkdown() {
  return `${GENERATED_HEADER}

# AI Acceleration Plane

Read \`.ai/BOOTSTRAP.md\`, then resolve task context:

\`\`\`bash
npm run knowledge:context -- --task="<exact task>"
\`\`\`

Canonical truth lives outside \`.ai/\`. Regenerate with \`npm run knowledge:build\`;
validate freshness with \`npm run knowledge:validate\`.
`;
}

function authorityOrderMarkdown() {
  return `${GENERATED_HEADER}

# Authority Order

1. Security and privacy policy.
2. Active ADRs.
3. Normative rules.
4. Public contracts and schemas.
5. Module documentation.
6. Source and tests.
7. Generated summaries.

Generated summaries never override canonical sources.
`;
}

function riskLanesMarkdown() {
  return `${GENERATED_HEADER}

# Risk Lanes

## Routine

Localized UI or documentation changes with no contract impact.
Gates: targeted tests, lint, typecheck.

## Standard

Feature behavior, dependency, API adapter, storage, routing, native plugin, or package owner
changes. Gates: routine + coverage, architecture, ownership, build.

## Critical

Authentication, token handling, permissions, deep links, secure storage, native release,
destructive migration, secrets, privacy, or security policy.
Gates: standard + integration/contract suites, security:audit, security:secrets, E2E.

Context breadth and validation expand with risk.
`;
}

function contextRouterSpecMarkdown() {
  return `${GENERATED_HEADER}

# Context Router Specification

Input: exact task text; optional --files, --symbols, --diff selectors.

Output: owning module(s), relevant rules, the most relevant skill, active ADRs, source owners,
direct tests, risks (known pitfalls), required validation gates, and documentation deltas.

The resolver is a routing aid. It is not proof; read the resolved sources.
`;
}

function moduleGraph() {
  const modules = existsSync('src/modules') ? readdirSync('src/modules') : [];
  return {
    generated: true,
    modules: modules.map((name) => {
      const indexPath = `src/modules/${name}/index.ts`;
      const indexSource = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : '';
      const exportedNames = [...indexSource.matchAll(/export\s+\{([^}]+)\}/gu)]
        .flatMap((match) => match[1].split(','))
        .map((name_) => name_.replace(/\btype\b/u, '').trim())
        .filter((name_) => name_ !== '')
        .sort();
      return { name, publicSurface: exportedNames };
    }),
  };
}

function ownershipGraph() {
  return {
    generated: true,
    ownership: PACKAGE_OWNERSHIP.map(({ vendor, owner, ownerDirs }) => ({
      vendor,
      owner,
      ownerDirs,
    })),
  };
}

function layersGraph() {
  return {
    generated: true,
    direction: 'app -> modules -> platform -> shared -> packages -> vendors',
    allowedImports: {
      app: ['app', 'modules', 'platform', 'shared', 'packages'],
      modules: ['modules(public surface)', 'platform', 'shared', 'packages'],
      platform: ['platform', 'shared', 'packages'],
      shared: ['shared', 'packages'],
      packages: ['packages'],
    },
  };
}

const PACKS = {
  'feature-work': {
    title: 'New feature / module work',
    entries: [
      'rules/01-architecture-and-dependency-direction.md',
      'rules/02-feature-modules.md',
      'rules/03-components.md',
      'rules/05-hooks-and-effects.md',
      'skills/new-feature-module.md',
      'context/architecture-map.md',
      'context/module-anatomy.md',
    ],
  },
  'api-work': {
    title: 'HTTP / NestJS API work',
    entries: [
      'rules/13-http-and-nest-api.md',
      'rules/17-error-handling.md',
      'skills/axios-endpoint.md',
      'skills/nest-dto-integration.md',
      'context/api-flow.md',
      'docs/api/nest-error-contract.md',
      'architecture/adrs/0007-axios-nest-api-boundary.md',
    ],
  },
  'native-work': {
    title: 'Capacitor / native work',
    entries: [
      'rules/11-capacitor-native-boundaries.md',
      'rules/26-native-release-readiness.md',
      'skills/capacitor-plugin.md',
      'skills/native-listener.md',
      'context/native-capability-map.md',
      'docs/native/android-runbook.md',
      'memory/native-pitfalls.md',
    ],
  },
  'ui-work': {
    title: 'Design-system / UI work',
    entries: [
      'rules/03-components.md',
      'rules/04-containers.md',
      'rules/19-accessibility.md',
      'rules/21-i18n-rtl.md',
      'skills/component.md',
      'context/state-ownership-map.md',
    ],
  },
  'testing-work': {
    title: 'Testing / coverage work',
    entries: [
      'rules/22-testing-and-coverage.md',
      'skills/unit-test.md',
      'skills/integration-test.md',
      'skills/playwright-test.md',
      'context/test-strategy-map.md',
      'testing/README.md',
    ],
  },
  'security-work': {
    title: 'Auth / security work (critical lane)',
    entries: [
      'rules/18-security.md',
      'rules/12-routing-and-deep-links.md',
      'skills/secure-storage.md',
      'skills/security-review.md',
      'context/auth-flow.md',
      'docs/security/token-storage.md',
      'architecture/adrs/0010-secure-token-storage.md',
    ],
  },
};

function packMarkdown(key, pack) {
  const lines = pack.entries.map((entry) =>
    existsSync(entry) ? `- ${entry}` : `- ${entry} (missing — create it)`,
  );
  return `${GENERATED_HEADER}

# Pack: ${pack.title}

Read in order:

${lines.join('\n')}
`;
}

export function buildKnowledge({
  graphsOnly = false,
  packsOnly = false,
  incremental = false,
} = {}) {
  const inventory = buildInventory();
  if (incremental && existsSync('.ai/manifest.json')) {
    const previous = JSON.parse(readFileSync('.ai/manifest.json', 'utf8'));
    if (JSON.stringify(previous.files) === JSON.stringify(inventory)) {
      console.log('knowledge:build --incremental: canonical sources unchanged; skipping.');
      return;
    }
  }
  if (!packsOnly) {
    writeGenerated('.ai/graphs/modules.json', JSON.stringify(moduleGraph(), null, 2));
    writeGenerated('.ai/graphs/ownership.json', JSON.stringify(ownershipGraph(), null, 2));
    writeGenerated('.ai/graphs/layers.json', JSON.stringify(layersGraph(), null, 2));
  }
  if (!graphsOnly) {
    for (const [key, pack] of Object.entries(PACKS)) {
      writeGenerated(`.ai/packs/${key}.md`, packMarkdown(key, pack));
    }
  }
  if (!graphsOnly && !packsOnly) {
    writeGenerated('.ai/BOOTSTRAP.md', bootstrapMarkdown());
    writeGenerated('.ai/README.md', readmeMarkdown());
    writeGenerated('.ai/authority-order.md', authorityOrderMarkdown());
    writeGenerated('.ai/risk-lanes.md', riskLanesMarkdown());
    writeGenerated('.ai/context-router-spec.md', contextRouterSpecMarkdown());
    const canonicalCount = Object.keys(inventory).length;
    writeGenerated(
      '.ai/reports/knowledge-report.json',
      JSON.stringify(
        {
          generated: true,
          governanceVersion: GOVERNANCE_VERSION,
          canonicalFileCount: canonicalCount,
          packs: Object.keys(PACKS).sort(),
        },
        null,
        2,
      ),
    );
    writeGenerated(
      '.ai/manifest.json',
      JSON.stringify(
        {
          generated: true,
          governanceVersion: GOVERNANCE_VERSION,
          entrypoint: '.ai/BOOTSTRAP.md',
          canonicalRoots: [
            'rules',
            'skills',
            'agents',
            'context',
            'memory',
            'architecture/adrs',
            'docs',
          ],
          files: inventory,
        },
        null,
        2,
      ),
    );
  }
  console.log('knowledge:build completed.');
}
