import {
  MOCK_ASSESSMENTS_TEAM_ID,
  MOCK_CATEGORY_IDS,
  MOCK_METRIC_IDS,
  MOCK_PERIOD_IDS,
  MOCK_SCALE_IDS,
  MOCK_TEMPLATE_ID,
} from './assessments-data.fixture';

/** Deterministic assessment catalog: categories, scales, metrics, templates, periods. */
export const MOCK_CATEGORIES = [
  {
    id: MOCK_CATEGORY_IDS.athletic,
    key: 'athletic',
    name: 'Athletic',
    description: 'Speed, power, and stamina.',
    sortOrder: 1,
  },
  {
    id: MOCK_CATEGORY_IDS.offense,
    key: 'offense',
    name: 'Offense',
    description: 'Cutting, throwing, and decisions with the disc.',
    sortOrder: 2,
  },
  {
    id: MOCK_CATEGORY_IDS.defense,
    key: 'defense',
    name: 'Defense',
    description: 'Marking, positioning, and help defence.',
    sortOrder: 3,
  },
  {
    id: MOCK_CATEGORY_IDS.mental,
    key: 'mental',
    name: 'Mental',
    description: 'Attitude, resilience, and team spirit.',
    sortOrder: 4,
  },
];

export const MOCK_SCALES = [
  {
    id: MOCK_SCALE_IDS.score,
    key: 'legacy-0-5',
    name: 'Evaluator 0–5',
    valueKind: 'legacy_0_5',
    unit: null,
    minimumValue: 0,
    maximumValue: 5,
    stepValue: 1,
    categoricalOptions: [],
    guidance: 'Score against the published rubric; leave blank when not observed.',
  },
  {
    id: MOCK_SCALE_IDS.timed,
    key: 'timed-seconds',
    name: 'Timed (seconds)',
    valueKind: 'timed',
    unit: 's',
    minimumValue: 0,
    maximumValue: 60,
    stepValue: 0.1,
    categoricalOptions: [],
    guidance: 'Stopwatch time over the marked distance.',
  },
  {
    id: MOCK_SCALE_IDS.text,
    key: 'free-text',
    name: 'Free text',
    valueKind: 'text',
    unit: null,
    minimumValue: null,
    maximumValue: null,
    stepValue: null,
    categoricalOptions: [],
    guidance: 'Describe what you observed.',
  },
];

export const MOCK_METRICS = [
  {
    id: MOCK_METRIC_IDS.speed,
    categoryId: MOCK_CATEGORY_IDS.athletic,
    scaleId: MOCK_SCALE_IDS.score,
    key: 'speed',
    name: 'Speed',
    definition: 'Acceleration and top-end speed over 40 metres.',
    direction: 'higher_is_better',
    guidance: 'Compare against the squad baseline for the age group.',
    tags: ['objective'],
    status: 'active',
  },
  {
    id: MOCK_METRIC_IDS.power,
    categoryId: MOCK_CATEGORY_IDS.athletic,
    scaleId: MOCK_SCALE_IDS.score,
    key: 'strength-power',
    name: 'Strength and power',
    definition: 'Approved strength/power metric — never inferred from speed.',
    direction: 'higher_is_better',
    guidance: 'Only score when a strength session was observed.',
    tags: ['objective'],
    status: 'active',
  },
  {
    id: MOCK_METRIC_IDS.stamina,
    categoryId: MOCK_CATEGORY_IDS.athletic,
    scaleId: MOCK_SCALE_IDS.timed,
    key: 'stamina',
    name: 'Stamina',
    definition: 'Sustained output across a full point.',
    direction: 'lower_is_better',
    guidance: 'Beep-test equivalent in seconds.',
    tags: ['external'],
    status: 'active',
  },
  {
    id: MOCK_METRIC_IDS.offense,
    categoryId: MOCK_CATEGORY_IDS.offense,
    scaleId: MOCK_SCALE_IDS.score,
    key: 'offense',
    name: 'Offense',
    definition: 'Cutting timing, throw selection, and completion under pressure.',
    direction: 'higher_is_better',
    guidance: 'Weight decisions above raw completions.',
    tags: ['match'],
    status: 'active',
  },
  {
    id: MOCK_METRIC_IDS.defense,
    categoryId: MOCK_CATEGORY_IDS.defense,
    scaleId: MOCK_SCALE_IDS.score,
    key: 'defense',
    name: 'Defense',
    definition: 'Marking discipline, positioning, and help defence.',
    direction: 'higher_is_better',
    guidance: 'Reward the disciplined mark over the highlight block.',
    tags: ['match'],
    status: 'active',
  },
  {
    id: MOCK_METRIC_IDS.attitude,
    categoryId: MOCK_CATEGORY_IDS.mental,
    scaleId: MOCK_SCALE_IDS.score,
    key: 'attitude',
    name: 'Attitude',
    definition: 'Coachability, spirit, and resilience after a turnover.',
    direction: 'higher_is_better',
    guidance: 'Coach judgement; note the evidence you relied on.',
    tags: ['subjective'],
    status: 'active',
  },
];

export const MOCK_TEMPLATES = [
  {
    id: MOCK_TEMPLATE_ID,
    teamId: MOCK_ASSESSMENTS_TEAM_ID,
    key: 'senior-2026',
    name: 'Senior squad 2026',
    status: 'published',
    version: 2,
    metrics: [
      { metricDefinitionId: MOCK_METRIC_IDS.speed, required: true, sortOrder: 1 },
      { metricDefinitionId: MOCK_METRIC_IDS.power, required: true, sortOrder: 2 },
      { metricDefinitionId: MOCK_METRIC_IDS.stamina, required: false, sortOrder: 3 },
      { metricDefinitionId: MOCK_METRIC_IDS.offense, required: true, sortOrder: 4 },
      { metricDefinitionId: MOCK_METRIC_IDS.defense, required: true, sortOrder: 5 },
      { metricDefinitionId: MOCK_METRIC_IDS.attitude, required: false, sortOrder: 6 },
    ],
  },
];

export const MOCK_PERIODS = [
  {
    id: MOCK_PERIOD_IDS.spring,
    teamId: MOCK_ASSESSMENTS_TEAM_ID,
    templateId: MOCK_TEMPLATE_ID,
    name: 'Spring 2026',
    startsOn: '2026-03-01',
    endsOn: '2026-05-31',
    status: 'archived',
  },
  {
    id: MOCK_PERIOD_IDS.summer,
    teamId: MOCK_ASSESSMENTS_TEAM_ID,
    templateId: MOCK_TEMPLATE_ID,
    name: 'Summer 2026',
    startsOn: '2026-06-01',
    endsOn: '2026-08-31',
    status: 'active',
  },
];
